// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdDfufFQo2rQL0ctawNW4pPs_alXaqEj4',
    appId: '1:252100203309:web:59efd7940a7969c4d4f9a4',
    messagingSenderId: '252100203309',
    projectId: 'socialapp-5b92e',
    authDomain: 'socialapp-5b92e.firebaseapp.com',
    storageBucket: 'socialapp-5b92e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMOKqYtydpKwblvV58-zigvuzHKrVYN20',
    appId: '1:252100203309:android:033d53d5e4a3c18fd4f9a4',
    messagingSenderId: '252100203309',
    projectId: 'socialapp-5b92e',
    storageBucket: 'socialapp-5b92e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBE1wIphF6P3AWo8JmO6iWiqEOnxfJoqbI',
    appId: '1:252100203309:ios:3fac1bafac0f9a10d4f9a4',
    messagingSenderId: '252100203309',
    projectId: 'socialapp-5b92e',
    storageBucket: 'socialapp-5b92e.appspot.com',
    iosBundleId: 'com.example.socialMediaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBE1wIphF6P3AWo8JmO6iWiqEOnxfJoqbI',
    appId: '1:252100203309:ios:458c3a63668151d6d4f9a4',
    messagingSenderId: '252100203309',
    projectId: 'socialapp-5b92e',
    storageBucket: 'socialapp-5b92e.appspot.com',
    iosBundleId: 'com.example.socialMediaApp.RunnerTests',
  );
}
